# Change these first
owner: adamab48 # Your GitHub organization or username, where this repository lives
repo: celestia-uptime # The name of this repository

sites:
  - name: ADMIN-API PROD
    url: https://admin-api.prod.celestia.elmenu.tn
  - name: ADMIN-API STAGING
    url: https://admin-api.staging.celestia.elmenu.tn
  - name: ADMIN-UI PROD
    url: https://admin-ui.prod.celestia.elmenu.tn
  - name: ADMIN-UI STAGING
    url: https://admin-ui.staging.celestia.elmenu.tn
  - name: API STAGING
    url: https://staging.celestia.elmenu.tn
  - name: API PROD
    url: https://prod.celestia.elmenu.tn
  - name: TRACING
    url: https://celestia-tracing.onrender.com
  - name: HOMEPAGE
    url: https://home.celestia.elmenu.tn

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.celestia.elmenu.tn
  # baseUrl: /your-repo-name
  logoUrl: https://play-lh.googleusercontent.com/1gr2wUGNisftEIv3y6ze-QxpIb2oerX2aMq0Lh03Nz--SqXMbrnmoEIPQDUV9HaAKtuH=w480-h960-rw
  name: Celestia Uptime
  introTitle: "**Celestia Uptime**"
  introMessage: This is a sample status page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
